# Generated by Django 4.1.6 on 2023-08-19 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display_title',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='label',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
