# Generated by Django 4.1.6 on 2023-08-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0002_article_display_title_article_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display_author',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
