# Generated by Django 4.1.6 on 2023-08-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0004_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
    ]
