# Generated by Django 4.1.6 on 2023-08-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0006_concert'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='contact',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
