# Generated by Django 4.1.6 on 2023-08-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0007_concert_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='image_ref',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
