# Generated by Django 4.1.6 on 2023-09-03 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0008_concert_image_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_reference', models.CharField(blank=True, default='', max_length=256)),
                ('image_path', models.CharField(blank=True, default='', max_length=256)),
                ('image_short', models.CharField(blank=True, default='', max_length=256)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('ox', models.PositiveIntegerField(blank=True, default=0)),
                ('oy', models.PositiveIntegerField(blank=True, default=0)),
                ('ow', models.PositiveIntegerField(blank=True, default=150)),
                ('oh', models.PositiveIntegerField(blank=True, default=150)),
            ],
        ),
    ]
