# Generated by Django 4.1.6 on 2023-09-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0009_galleryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image_path',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image_reference',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image_short',
            field=models.CharField(default='', max_length=256),
        ),
    ]
