# Generated by Django 4.1.6 on 2023-09-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0010_alter_galleryitem_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image_reference',
            field=models.CharField(max_length=256),
        ),
    ]
