# Generated by Django 4.1.6 on 2023-09-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0012_alter_galleryitem_image_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='pub_date',
        ),
    ]
