# Generated by Django 4.1.6 on 2023-09-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0013_remove_galleryitem_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='oh',
            field=models.PositiveIntegerField(blank=True, default=60),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='ow',
            field=models.PositiveIntegerField(blank=True, default=15),
        ),
    ]
