# Generated by Django 4.1.6 on 2023-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0014_alter_galleryitem_oh_alter_galleryitem_ow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='oh',
            field=models.PositiveIntegerField(blank=True, default=360),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='ow',
            field=models.PositiveIntegerField(blank=True, default=120),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='ox',
            field=models.PositiveIntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='oy',
            field=models.PositiveIntegerField(blank=True, default=40),
        ),
    ]
