# Generated by Django 4.1.6 on 2023-09-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0015_alter_galleryitem_oh_alter_galleryitem_ow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='not_found',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
