# Generated by Django 4.1.6 on 2023-10-11 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0016_galleryitem_not_found'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('label', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.TextField(blank=True, default='', max_length=4096)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.CharField(blank=True, default='', max_length=256)),
                ('display_title', models.BooleanField(blank=True, default=False)),
                ('display_author', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
