# Generated by Django 4.1.6 on 2023-10-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0017_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pages',
            field=models.ManyToManyField(to='frontdoor.page'),
        ),
    ]
