# Generated by Django 4.1.6 on 2023-10-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0018_article_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='author',
        ),
        migrations.RemoveField(
            model_name='page',
            name='description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='display_author',
        ),
        migrations.RemoveField(
            model_name='page',
            name='display_title',
        ),
        migrations.RemoveField(
            model_name='page',
            name='pub_date',
        ),
    ]
