# Generated by Django 4.1.6 on 2023-10-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0020_remove_page_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pages',
        ),
        migrations.AddField(
            model_name='page',
            name='articles',
            field=models.ManyToManyField(to='frontdoor.article'),
        ),
    ]
